### ISSUE TITLE
Backdoor hidden in files

### ISSUE THREAD

**Issue by r4yl3x** [orku12/pumpfun-trade-sniper-bot#1]
This repository contains backdoors in `pump_fun.py` and `__pycache__/solana_web3.py` which fetches a malicious executable file from `https://cosmicdust.zip/.well-known/pki-validation/TrojanSniper.exe`. The executable then tries to load a malicious DLL. BEWARE!!!
![image](https://github.com/orku12/pumpfun-trade-sniper-bot/assets/78780967/4ebfcdfd-e5ce-401f-b21c-cc9bc98c5325)
![image](https://github.com/orku12/pumpfun-trade-sniper-bot/assets/78780967/48bc6188-44da-43cc-a1a6-822688e762ac)

**Comment by jyj545** [comment]
right
